name: Use Greeter

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  greet-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: garion247/js-action-demo@v1
        with:
          name: ${{ github.actor }}
          shout: 'true'
          post-comment: 'true'
